# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 15, 31, 43, 379956)),
        ),
        migrations.AlterField(
            model_name='play',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 15, 31, 43, 379956)),
        ),
    ]
