# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170719_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='play',
            name='time_start',
        ),
        migrations.AddField(
            model_name='play',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 16, 49, 15, 472703)),
        ),
    ]
