# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20170719_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 17, 11, 52, 504426)),
        ),
    ]
