# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20170719_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('next_clue', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Player'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='beacon',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 17, 43, 59, 673616)),
        ),
        migrations.AlterField(
            model_name='play',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 17, 43, 59, 672615)),
        ),
        migrations.AddField(
            model_name='trivia',
            name='artefact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Artefact'),
        ),
        migrations.AddField(
            model_name='theme',
            name='artefact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Artefact'),
        ),
        migrations.AddField(
            model_name='image',
            name='trivia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Trivia'),
        ),
    ]
