# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20170719_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='play',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Play'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 17, 44, 20, 794948)),
        ),
        migrations.AlterField(
            model_name='play',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 17, 44, 20, 793946)),
        ),
    ]
